const Doctor = require('../models/Doctor');
const DoctorAvailability = require('../models/DoctorAvailability');

// Get all doctors
exports.getAllDoctors = async (req, res) => {
    try {
        const { type, isActive } = req.query;
        const filter = {};

        if (type) filter.type = type;
        if (isActive !== undefined) filter.isActive = isActive === 'true';

        const doctors = await Doctor.find(filter).populate('categories').sort({ priority: -1, name: 1 });
        res.json(doctors);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching doctors', error: error.message });
    }
};

// Get single doctor
exports.getDoctorById = async (req, res) => {
    try {
        const doctor = await Doctor.findById(req.params.id).populate('categories');
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }
        res.json(doctor);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching doctor', error: error.message });
    }
};

// Create doctor
exports.createDoctor = async (req, res) => {
    try {
        const doctor = new Doctor(req.body);
        await doctor.save();
        await doctor.populate('categories');
        res.status(201).json(doctor);
    } catch (error) {
        res.status(400).json({ 
            message: 'Error saving doctor', 
            error: error.message 
        });
    }
};

// Update doctor
exports.updateDoctor = async (req, res) => {
    try {
        const doctor = await Doctor.findByIdAndUpdate(
            req.params.id,
            req.body,
            { new: true, runValidators: true }
        ).populate('categories');
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }

        // Clean up future auto-generated availability records for this doctor to let them re-generate with new settings
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const todayUtc = new Date(today.toISOString().substring(0, 10) + 'T00:00:00.000Z');
        
        await DoctorAvailability.deleteMany({
            doctorId: doctor._id,
            date: { $gte: todayUtc },
            isAutoGenerated: true
        });

        res.json(doctor);
    } catch (error) {
        res.status(400).json({ message: 'Error updating doctor', error: error.message });
    }
};

// Delete doctor
exports.deleteDoctor = async (req, res) => {
    try {
        const doctor = await Doctor.findByIdAndDelete(req.params.id);
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }

        // Also delete all availability records for this doctor
        await DoctorAvailability.deleteMany({ doctorId: req.params.id });

        res.json({ message: 'Doctor deleted successfully' });
    } catch (error) {
        res.status(500).json({ message: 'Error deleting doctor', error: error.message });
    }
};

// Bulk update status for doctors
exports.bulkUpdateStatus = async (req, res) => {
    try {
        const { ids, isActive } = req.body;
        if (!ids || !Array.isArray(ids)) {
            return res.status(400).json({ message: 'ids must be an array' });
        }

        await Doctor.updateMany(
            { _id: { $in: ids } },
            { $set: { isActive, updatedAt: Date.now() } }
        );

        // Clean up future auto-generated availability records to let them re-generate with new active status
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const todayUtc = new Date(today.toISOString().substring(0, 10) + 'T00:00:00.000Z');
        
        await DoctorAvailability.deleteMany({
            doctorId: { $in: ids },
            date: { $gte: todayUtc },
            isAutoGenerated: true
        });

        res.json({ message: 'Doctors status updated successfully' });
    } catch (error) {
        res.status(500).json({ message: 'Error bulk updating status', error: error.message });
    }
};


