const Doctor = require('../models/Doctor');
const DoctorAvailability = require('../models/DoctorAvailability');

// Get all doctors
exports.getAllDoctors = async (req, res) => {
    try {
        const { type, isActive } = req.query;
        const filter = {};

        if (type) filter.type = type;
        if (isActive !== undefined) filter.isActive = isActive === 'true';

        const doctors = await Doctor.find(filter).populate('categories').sort({ priority: -1, name: 1 });
        res.json(doctors);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching doctors', error: error.message });
    }
};

// Get single doctor
exports.getDoctorById = async (req, res) => {
    try {
        const doctor = await Doctor.findById(req.params.id).populate('categories');
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }
        res.json(doctor);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching doctor', error: error.message });
    }
};

// Create doctor
exports.createDoctor = async (req, res) => {
    try {
        const doctor = new Doctor(req.body);
        await doctor.save();
        await doctor.populate('categories');
        res.status(201).json(doctor);
    } catch (error) {
        res.status(400).json({ 
            message: 'Error saving doctor', 
            error: error.message 
        });
    }
};

// Update doctor
exports.updateDoctor = async (req, res) => {
    try {
        const doctor = await Doctor.findByIdAndUpdate(
            req.params.id,
            req.body,
            { new: true, runValidators: true }
        ).populate('categories');
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }

        // Clean up future auto-generated availability records for this doctor to let them re-generate with new settings
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const todayUtc = new Date(today.toISOString().substring(0, 10) + 'T00:00:00.000Z');
        
        await DoctorAvailability.deleteMany({
            doctorId: doctor._id,
            date: { $gte: todayUtc },
            isAutoGenerated: true
        });

        res.json(doctor);
    } catch (error) {
        res.status(400).json({ message: 'Error updating doctor', error: error.message });
    }
};

// Delete doctor
exports.deleteDoctor = async (req, res) => {
    try {
        const doctor = await Doctor.findByIdAndDelete(req.params.id);
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }

        // Also delete all availability records for this doctor
        await DoctorAvailability.deleteMany({ doctorId: req.params.id });

        res.json({ message: 'Doctor deleted successfully' });
    } catch (error) {
        res.status(500).json({ message: 'Error deleting doctor', error: error.message });
    }
};

// Toggle emergency availability
exports.toggleEmergencyAvailability = async (req, res) => {
    try {
        const doctor = await Doctor.findById(req.params.id);
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor not found' });
        }

        doctor.isEmergencyAvailable = !doctor.isEmergencyAvailable;
        await doctor.save();

        res.json(doctor);
    } catch (error) {
        res.status(500).json({ message: 'Error toggling emergency availability', error: error.message });
    }
};

// Get emergency available doctors based on TODAY's schedule
exports.getEmergencyDoctors = async (req, res) => {
    try {
        // 1. Get today's date (start of day)
        const today = new Date();
        today.setHours(0, 0, 0, 0);

        // 2. Find availability records for today having emergencyAvailable: true
        // and populate the doctor details
        const availabilities = await DoctorAvailability.find({
            date: today,
            emergencyAvailable: true,
            isEnabled: true
        }).populate('doctorId');

        // 3. Extract doctors from the availability records
        // Filter out any where doctorId might be null (if doctor was deleted) or inactive
        const doctors = availabilities
            .map(a => a.doctorId)
            .filter(d => d && d.isActive)
            .sort((a, b) => {
                // Sort by priority (high to low) then name (A-Z)
                if ((a.priority || 0) !== (b.priority || 0)) {
                    return (b.priority || 0) - (a.priority || 0);
                }
                return a.name.localeCompare(b.name);
            });

        res.json(doctors);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching emergency doctors', error: error.message });
    }
};
